#!/usr/bin/env python3
"""
Update Crons - Register all intelligence script cron jobs
"""
import subprocess
import sys
from pathlib import Path


def get_cron_jobs():
    """Define all cron jobs for intelligence scripts"""
    scripts_dir = Path(__file__).parent
    
    jobs = [
        {
            'name': 'daily_pulse_morning',
            'schedule': '0 8 * * *',
            'command': f'cd {scripts_dir} && /usr/bin/python3 daily_pulse.py >> /home/wner/clawd/logs/daily_pulse.log 2>&1',
            'description': 'Morning pulse (8:00)'
        },
        {
            'name': 'daily_pulse_afternoon',
            'schedule': '0 13 * * *',
            'command': f'cd {scripts_dir} && /usr/bin/python3 daily_pulse.py >> /home/wner/clawd/logs/daily_pulse.log 2>&1',
            'description': 'Afternoon pulse (13:00)'
        },
        {
            'name': 'daily_pulse_evening',
            'schedule': '0 18 * * *',
            'command': f'cd {scripts_dir} && /usr/bin/python3 daily_pulse.py >> /home/wner/clawd/logs/daily_pulse.log 2>&1',
            'description': 'Evening pulse (18:00)'
        },
        {
            'name': 'weekly_digest',
            'schedule': '0 9 * * 1',
            'command': f'cd {scripts_dir} && /usr/bin/python3 weekly_digest.py >> /home/wner/clawd/logs/weekly_digest.log 2>&1',
            'description': 'Weekly digest (Monday 9:00)'
        },
        {
            'name': 'weekly_wrap',
            'schedule': '0 20 * * 5',
            'command': f'cd {scripts_dir} && /usr/bin/python3 weekly_wrap.py >> /home/wner/clawd/logs/weekly_wrap.log 2>&1',
            'description': 'Weekly wrap (Friday 20:00)'
        },
    ]
    
    return jobs


def remove_existing_jobs():
    """Remove existing intelligence cron jobs"""
    job_names = [j['name'] for j in get_cron_jobs()]
    
    for name in job_names:
        try:
            result = subprocess.run(
                ['crontab', '-l'],
                capture_output=True,
                text=True
            )
            
            if result.returncode == 0:
                lines = result.stdout.split('\n')
                new_lines = [line for line in lines if not any(name in line for name in job_names)]
                
                if len(lines) != len(new_lines):
                    subprocess.run(
                        ['crontab', '-'],
                        input='\n'.join(new_lines),
                        text=True
                    )
                    print(f"✓ Removed existing job: {name}")
        except Exception as e:
            print(f"Note: Could not remove {name}: {e}")


def install_cron_jobs():
    """Install all cron jobs"""
    jobs = get_cron_jobs()
    
    print("\n🕐 INTELLIGENCE SCRIPTS - CRON INSTALLATION")
    print("=" * 50)
    
    # First remove existing jobs
    remove_existing_jobs()
    
    # Build new crontab
    cron_lines = []
    
    # Add comment header
    cron_lines.append("# Intelligence Scripts Cron Jobs")
    cron_lines.append("# Generated by update_crons.py")
    cron_lines.append("")
    
    # Add each job
    for job in jobs:
        cron_lines.append(f"# {job['description']}")
        cron_lines.append(f"{job['schedule']} {job['command']}")
        cron_lines.append("")
    
    # Get existing crontab (without intelligence jobs)
    try:
        result = subprocess.run(
            ['crontab', '-l'],
            capture_output=True,
            text=True
        )
        existing = result.stdout if result.returncode == 0 else ""
    except:
        existing = ""
    
    # Filter out intelligence job comments from existing
    filtered_existing = []
    for line in existing.split('\n'):
        if not any(job['name'] in line for job in get_cron_jobs()):
            filtered_existing.append(line)
    
    # Combine
    all_lines = filtered_existing + cron_lines
    new_cron = '\n'.join(all_lines)
    
    # Install
    try:
        subprocess.run(
            ['crontab', '-'],
            input=new_cron,
            text=True
        )
        print("✓ Cron jobs installed successfully!\n")
    except Exception as e:
        print(f"✗ Failed to install cron jobs: {e}")
        return False
    
    # List installed jobs
    print("📋 Installed Jobs:")
    print("-" * 50)
    for job in jobs:
        print(f"  {job['schedule']} → {job['description']}")
    print("-" * 50)
    
    # Ensure log directory exists
    log_dir = Path('/home/wner/clawd/logs')
    log_dir.mkdir(exist_ok=True)
    print(f"\n✓ Log directory: {log_dir}")
    
    return True


def list_cron_jobs():
    """List current cron jobs"""
    try:
        result = subprocess.run(['crontab', '-l'], capture_output=True, text=True)
        if result.returncode == 0:
            print("\n📋 Current Crontab:")
            print("-" * 50)
            print(result.stdout)
            print("-" * 50)
        else:
            print("No crontab installed")
    except Exception as e:
        print(f"Error listing crontab: {e}")


if __name__ == "__main__":
    action = sys.argv[1] if len(sys.argv) > 1 else 'install'
    
    if action == 'install':
        success = install_cron_jobs()
        if success:
            list_cron_jobs()
    elif action == 'list':
        list_cron_jobs()
    elif action == 'remove':
        remove_existing_jobs()
        print("✓ Intelligence cron jobs removed")
    else:
        print(f"Unknown action: {action}")
        print("Usage: update_crons.py [install|list|remove]")
